services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '80:8080'
  database:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_PASSWORD: superPassword
      POSTGRES_DB: car_service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d car_service"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

